
The base dimension of your u-net should ideally be no smaller than 128, as recommended by a professional DDPM trainer https://nonint.com/2022/05/04/friends-dont-let-friends-train-small-diffusion-models/
Epoch 1/5
--- Unet 1 ---
Traceback (most recent call last):
  File "/home/azureuser/imagen/spaceforge/train.py", line 269, in <module>
    run_train_loop(cfg, trainer, loader, device, i=cfg["train"]["unet_number"])
  File "/home/azureuser/imagen/spaceforge/train.py", line 143, in run_train_loop
    train(cfg, dataloader, trainer, epoch, i, device)
  File "/home/azureuser/imagen/spaceforge/train.py", line 67, in train
    for step, batch in enumerate(dataloader):
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/webdataset/iterators.py", line 304, in to_tuple
    for sample in data:
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/webdataset/iterators.py", line 284, in map_dict
    for sample in data:
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/webdataset/iterators.py", line 261, in rename
    if handler(exn):
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/webdataset/handlers.py", line 24, in reraise_exception
    raise exn
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/webdataset/iterators.py", line 258, in rename
    result.update({k: getfirst(sample, v, missing_is_error=True) for k, v in kw.items()})
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/webdataset/iterators.py", line 258, in <dictcomp>
    result.update({k: getfirst(sample, v, missing_is_error=True) for k, v in kw.items()})
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/webdataset/iterators.py", line 83, in getfirst
    raise ValueError(f"didn't find {keys} in {list(a.keys())}")
ValueError: didn't find ['png'] in ['__key__', '__url__', '__worker__', '__rank__', '__nodeinfo__', 'jpg', 'json', 'txt']