
The base dimension of your u-net should ideally be no smaller than 128, as recommended by a professional DDPM trainer https://nonint.com/2022/05/04/friends-dont-let-friends-train-small-diffusion-models/
Epoch 1/8
--- Unet 1 ---
<torch.utils.data.dataloader.DataLoader object at 0x7f7751809070>
Traceback (most recent call last):
  File "/home/azureuser/imagen/spaceforge/train.py", line 269, in <module>
    run_train_loop(cfg, trainer, loader, device, i=cfg["train"]["unet_number"])
  File "/home/azureuser/imagen/spaceforge/train.py", line 144, in run_train_loop
    train(cfg, dataloader, trainer, epoch, i, device)
  File "/home/azureuser/imagen/spaceforge/train.py", line 68, in train
    for step, batch in enumerate(dataloader):
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/webdataset/pipeline.py", line 68, in iterator
    for sample in self.iterator1():
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/webdataset/filters.py", line 382, in _to_tuple
    for sample in data:
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/webdataset/filters.py", line 365, in _map_dict
    if handler(exn):
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/webdataset/filters.py", line 79, in reraise_exception
    raise exn
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/webdataset/filters.py", line 363, in _map_dict
    sample[k] = f(sample[k])
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/torchvision/transforms/transforms.py", line 94, in __call__
    img = t(img)
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/torchvision/transforms/transforms.py", line 349, in forward
    return F.resize(img, self.size, self.interpolation, self.max_size, self.antialias)
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/torchvision/transforms/functional.py", line 430, in resize
    return F_pil.resize(img, size=size, interpolation=pil_interpolation, max_size=max_size)
  File "/home/azureuser/miniconda3/envs/imagen/lib/python3.9/site-packages/torchvision/transforms/functional_pil.py", line 249, in resize
    raise TypeError(f"img should be PIL Image. Got {type(img)}")
TypeError: img should be PIL Image. Got <class 'numpy.ndarray'>