Traceback (most recent call last):
  File "/home/azureuser/imagen/spaceforge/train.py", line 219, in <module>
    cosine_sim_attn = cfg["model"]["unet1"]["cosine_sim_attn"],
KeyError: 'cosine_sim_attn'